manifests/view.pp
templates/view.erb

To achieve a setup I wanted to try (separate views for resolver and authoritative server role), I had to add two tweaks to the view class, since views used the same order value for all fragments (bind evaluates until first match, so order matters), and match-recursive-only was not supported.
P.S.: love your module, saved me a ton of time

add controllable order and support for match-recursive-only to views

---

lib/puppet/parser/functions/hmac_secret.rb
manifests/init.pp
manifests/key.pp
manifests/params.pp
templates/key.conf.erb
templates/named.conf.erb

Rely on BIND's default behavior for configuring named's 'control' clause and rndc and just generate an rndc.key. In the case that the platform does this, it's a replace => false file resource anyway.

Configure rndc correctly

---

lib/puppet/type/dns_rr.rb
lib/puppet/type/resource_record.rb

adds the record type DS (Delegation Signer), necessary for explicit management for delegating subdomains within DNSSEC-secured zones to establish a trust chain.
Example usage:
```
dns::record { 'sub.example.org-ds':
record => 'sub.example.org',
type   => 'DS',
data   => ['64098 5 2 A27B47D72633FAF62BC4C7D7E9142081BF87F3048EBFDC77892E3B8D C35B32E9'],
zone   => 'example.org',
}
```

Add record type DS

---

manifests/init.pp
templates/named.conf.erb

A very simple implementation of enabling the statistics channel, specify `statistics_port` to enable the listener on localhost. I think the feature is available since Bind 9.5.
One could probably go much more sophisticated with specifying listener IPs and access policies, but I really didn't need the complexity.

make statistics channel available for use if configured

---

data/osfamily/RedHat.yaml
manifests/params.pp
metadata.json

So here is the big one: I've added support for CentOS and thereby RedHat (compatible). I am running two named servers on CentOS 6 machines, so I can vouch for that version. I've had it running in a CentOS 7 test VM and I didn't get any errors, so it might work well there too. As to other Versions or other members of the RedHat osfamily (Scientific Linux etc) I can't really say much as I'm not running any systems with it.
I had to rework it quite a bit after the switch to hiera, but in the end it worked again.

CentOS / RedHat support

---

data/osfamily/Debian.yaml
data/osfamily/RedHat.yaml
manifests/init.pp
spec/classes/bind_spec.rb
spec/fixtures/hiera/common.yaml

Fix to specify the path to the main named.conf directly vs relative to the confdir as redhat derivatives use /etc/named.conf for the primary config file.
change the include for the params class to be fully qualified as currently it attempts to include ::params which fails the run.

Centos support

---

files/db.empty
manifests/zone.pp
templates/zone.conf.erb

Fix the zone template to prevent notify being added for stub zones as this creates an invalid zone.  Fix the zone defined type to prevent the zone file from being created  in the cache dir for stub zones.  With a stub zone you provide the master servers in the zone and bind will retrieve the NS records for that zone and create the zone file.  Creating the empty file causes the zone to be broken after the puppet run.  This is probably the case with a slave zone as well but don't have anything set up to test that right now.

Stub zones

---

lib/puppet_bind/provider/nsupdate.rb

Compute the adds and deletes required to get from existing RRData to new RRData
and perform just those operations instead of doing a complete drop/add of the
entire RRData set. Also during an update, do adds before deletes. This
eliminates the existence gap and fixes #29

Update RRData incrementally

---

README.md
lib/puppet/type/dns_rr.rb
lib/puppet/type/resource_record.rb
lib/puppet_bind/provider/nsupdate.rb

DNS queries for delegation records to poorly constructed zones won't have
answers, but they will have authority. Also, +nosearch

Allow response records from other sections

---

lib/puppet/type/resource_record.rb

I encountered a misleading error when passing invalid parameters to `resource_record`:
```
Error: Failed to apply catalog: Parameter record failed on Resource_record[xxxxx]: Validate method failed for class record: uninitialized constant Util at /path/to/my/manifest.pp:48
```
It seems that the recommended way to bubble up validation failures is `raise ArgumentError`: https://docs.puppetlabs.com/guides/custom_types.html#validation-and-munging

Improve error reporting

---

README.md
manifests/zone.pp
metadata.json
templates/zone.conf.erb

Add a parameter to `bind::zone` which indicates whether a zone is dynamic or
not. This has the effect of allowing puppet to manage the zone file rather than
simply initialize it. This change also introduces more appropriate handling of
slave and stub zones, so that puppet will not populate a stock zone file,
forcing the nameserver to do a zone transfer when a zone is created.
Also, there is now a substancial amount of validation in the `bind::zone` class
in order to prevent invalid parameter combinations, so that validity may be
assumed elsewhere in the manifest and in the configuration template.

Add `dynamic` parameter to `bind::zone`

---

manifests/zone.pp
templates/named.conf.erb

`dnssec-lookaside no;` is not accepted by BIND combined with `dnssec-enable no;`:
```
named[11385]: loading configuration from '/etc/bind/named.conf'
named[11385]: /etc/bind/named.conf:15: dnssec-lookaside 'no': non-root not yet supported
named[11385]: /etc/bind/named.conf:15: dnssec-lookaside requires either 'auto' or a domain and trust anchor
```
Updated the named.conf template to skip all further DNSSEC related options when `$dnssec => false`.
Also noticed a mismatched variable name in `bind::zone` and fixed.

Misc fixes

---

lib/puppet_bind/provider/nsupdate.rb

TXT and SPF record values have to be quoted in the nsupdate script in order to
preserve the integrity of the string.
Fixes #37

Automatic quote and unquote TXT and SPF

---

lib/puppet/type/resource_record.rb
lib/puppet_bind/provider/nsupdate.rb

This makes it possible to use resource_record with "standalone" keyfiles by introducing a keyfile parameter. Behaviour is unchanged if it is not specified.

Support custom keyfile paths

---

manifests/init.pp
spec/classes/bind_spec.rb

I found that the tools was also missing from Debian family. It is actually installed by default in everything but the minimal OS install which is why most would never see the issue. This commit addresses the missing package and adds rspec test for both Debian and RH family. 
Change-Id: I0b4680ce11fe604917fce654d68c2bec17c05438

Add missing bind tools package and improve rspec tests

---

manifests/init.pp

If we remove confdir files all the Debian standard files are purged and bind doesn't work

Don't remove confdir files this remove standard files

---

data/osfamily/Debian.yaml
data/osfamily/RedHat.yaml
manifests/init.pp
manifests/key.pp
manifests/params.pp
manifests/updater.pp
spec/fixtures/hiera/common.yaml

Fix a bunch of warnings whne using the bind::updater class by moving confdir to
the params class. In order for this to work, the bind and bind::updater classes
both now inherit from params. Also, fix the default value for
managed_key_directory to something that's actually falsey.

Put confdir in the params class, and more..

---

DEFAULT_ZONES.md
README.md
data/common.yaml
data/osfamily/RedHat.yaml
manifests/defaults.pp
manifests/init.pp
manifests/zone.pp

The changes in the `redhat-default-zones` branch, when released, may cause
upgrade difficulties for Red Hat system administrators. Try to ease the
transition.

Add upgrade warnings for Red Hat

---

lib/puppet/type/resource_record.rb

`Socket.ip_address_list` is a new addition to ruby 1.9. Maintain support for
ruby 1.8.7 by making the new autorequire feature of `resource_record`
conditional on the existence of the required API.

Check for API support for autorequire

---

files/dnssec-init
manifests/zone.pp
templates/zone.conf.erb

Fixes a bug in declaring a root zone. `.` does not work as a filename.

Root zone naming

---

manifests/zone.pp
templates/zone.conf.erb

e.g. Consul DNS uses port 8600
https://www.consul.io/docs/guides/forwarding.html
```
zone "consul" IN {
type forward;
forward only;
forwarders { 127.0.0.1 port 8600; };
};
```
This assumes that all the fowarders you are forwarding to are on the same port. If you are OK with the change but want it to support a parallel port array I might be able to figure that out.

support forwarding a zone to a dns server on port other than 53

---

manifests/view.pp
templates/view.erb

See: https://deepthought.isc.org/article/AA-00800/0/Automatic-empty-zones-including-RFC-1918-prefixes.html
Defaults to unspecified, as Bind's behaviour differs depending on (minor!) version, and whether recursion is enabled on a view.
Conflicts:
manifests/view.pp
templates/view.erb
fixes #84

Add allow-empty-zones support.

---

hiera.yaml
metadata.json

I am running your module without module_data using the built-in support for module data that is in the recent puppet versions. I am assuming this change wouldn't harm anyone using an older version of puppet but I haven't confirmed that. 
https://docs.puppetlabs.com/puppet/latest/reference/lookup_quick_module.html

support use of Puppet 4 module data

---

templates/zone.conf.erb

Allow the 'explicit' value of a zones notify config to be set as well as yes/no.

Allow 'explicit' zone notification

---

manifests/view.pp
templates/view.erb

Views support an `allow-transfer` directive essentially identical to the one in
zones. Copy the code from `manifests/zone.pp` and `templates/zone.conf.erb` to
support it.
Fixes #89

Add `allow-transfers` to views

---

lib/puppet/provider/dns_rr/nsupdate.rb
lib/puppet/provider/resource_record/nsupdate.rb

Some versions of Puppet suffer from a regression which prevents them from
successfully loading auxilliary code in the module's lib directory. See
https://tickets.puppetlabs.com/browse/SERVER-973
Fixes #80

Use a relative path load on LoadError

---

manifests/zone.pp
templates/zone.conf.erb

Allow master and slave zones (as well as forward as is currently allowed) to set forward and forwarders options.
This is so that this (https://kb.isc.org/article/AA-00538/0/How-can-I-disable-global-forwarding-for-delegated-subdomains.html) use case works.
To create an empty `forwarders { }; `option pass `forwarders => 'none'` to the zone.

Allow master/slave zones to set forwarders

---

data/common.yaml
manifests/init.pp
manifests/view.pp
manifests/zone.pp
templates/rndc-helper.erb
templates/view-mappings.erb

The `rndc` invocation in `bind::zone` needs to include class and view parameters when a zone is included in multiple views. Not an easy problem because the information isn't all available together during the puppet run.

Implement a helper script for zone reloads

---

manifests/init.pp
metadata.json

The newer version of the concat module seem to fix errors like:
The fragments directory is empty, cowardly refusing to make empty config files
Concat also has a parameter which will automatically put the "this file is managed by puppet" header in place.

Update to use at least the 2.0.0 version of puppetlabs-concat

---

data/osfamily/Debian.yaml
data/osfamily/RedHat.yaml
manifests/defaults.pp
manifests/init.pp
manifests/logging/category.pp
manifests/logging/channel.pp
templates/logging_channel.erb
templates/named.conf.erb

Adds `bind::logging::channel` and `bind::logging::category` defines in order to
support logging configuration.

Implement support for logging configuration

---

.fixtures.yml
.gitignore
spec/classes/bind_spec.rb
spec/classes/updater_spec.rb
spec/defines/key_spec.rb
spec/defines/zone_spec.rb
spec/fixtures/hiera/common.yaml
spec/fixtures/hiera/hiera.yaml
spec/spec_helper.rb

- Spec tests are now using the very useful rspec-puppet-facts that will iterate over all supported OS (listed from `metadata.json`)
- Resource coverage has been improved
- there are still classes/defines to be tested.

Feature: spec tests

---

manifests/init.pp
spec/classes/bind_spec.rb
templates/named.conf.erb

As suggested by @inkblot in #126, here are 2 new parameters : `tkey-gssapi-credential` and `tkey-domain` that defaults to `undef` so previous behaviour is respected.
Regards,

Additional parameters tkey-*

---

files/dnssec-init

Running dnssec-init manually gives an error:
/usr/local/bin/dnssec-init: line 15: [: !=: unary operator expected
It still completes successfully but looks a bit ugly.

add quotes to variables to fix "!=: unary operator expected"

---

templates/logging_channel.erb

`print-category`, `print-severity` and `print-time` options are not needed if the channel logging destination is set to `null`.

don't add print-* logging options if destination is null
